version: '3.1'
services:
  app:
    container_name: "stepfitnessappbackend"
    build: "./"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: "postgres:12"
    container_name: "stepfintessappdb"
    volumes:
      - C:\Users\0addys6n\Documents\StepAppBackupDir:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=password1"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=StepFitnessGame"
